---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - gem install travis
  - pip install -r requirements.txt

script:
  - molecule test

after_success:
  - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
  - chmod +x trigger.sh
  - ./trigger.sh codeyourinfra docker_compose master $TRAVIS_GITHUB_TOKEN

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: WfzYnIfjpBFx0p45HKcTBdQ0CiKWB2YkFi7KzRtq+HZTj8JzIyrGhy/XdLHIBv1pHDhvjokh3dcdOx0AxBQF0rjLZLx6kcjDWyoZW8U8XOMsqaIee0YiQcIzVPhRcNfabI+v42Xpbc/oAuuHQyhBLZZCGHgHSzZ0RkGgbwKG/6B0ySaw5fIdwZ9tpeVV68JAMo8TeWVATYjiPsrIPdRjMwkDO2KFrzr6WxjTzE+cXUh444mVQ0xnaRc+HavzW553axyM6HOz9KSUJ/YETZnI61imEyz5mLkQnze7HBPZHP9oRoJaAWo/m2xEa2W7YBA2TIS2Cx0PrlyrxNF9Y6Hbj2crwd6adqqcQF8J1kgfWtcMiEuKtioK94mzjzrSPvesmqkwpGDcUPaPqXsGHkToQB7QkpPwnVCODNqcqJTLn13gEwtlad33FNfkctr9i1+TiNEa4KJKM+OXhCpXOHivnk4zVzEcXBMTKM/c6O1al4MCIG3soFsOC/+UYLMNXk2JnaepLrAsZUM7rgoZf4Dtnr6ygIlKTZtz8cKdZbCwzjESC7IzAK0FlblpNoI0jGD+daav/4K8l/eotDItMasgIexq+6K4NaisLUnVGxfPMfe+2qB3hjOJtFsu1N7w+YbR54S8feoemy7h+BO0nI5CTeNfMiK4hAj89MWtfMCQ+kE=
